config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'main#index'

  devise_for :users, controllers: {
    sessions: 'auth/sessions',
    registrations: 'auth/registrations'
  }

  resources :categories do
    resources :articles do
      resources :comments
    end
    resources :banners, only: :index
  end

  get '/search', to: 'articles#search'

  resources :reactions
  resources :surveys
  resources :teams, only: [:index, :destroy] do
    member do
      post 'attach-to-user', to: 'teams#attach_to_user'
    end
  end

  get '/teams-search', to: 'teams#search'
  get '/team-hub', to: 'teams#team_hub'

  get '/survey/show_newest', to: 'surveys#show_newest'

  get '/profile', to: 'users#edit'
  put '/profile', to: 'users#update'
  patch '/newsletter/subscribe', to: 'users#subscribe_to_newsletter'

  get '/pages/:slug', to: 'pages#show'

  get '/locale/:locale', to: 'main#locale'

  namespace 'admin' do
    root 'home#index'
    put '/settings/:key', to: 'home#update'
    post 'home/photo_of_the_day', to: 'home#photo_of_the_day'
    resources :categories do
      member do
        get 'subcategories'
      end
      resources :articles
    end
    resources :users
    resources :locales
    resources :banners do
      member do
        put 'publish', to: 'banners#publish'
        put 'close', to: 'banners#close'
      end
    end
    resources :teams

    resources :surveys do
      member do
        put 'publish', to: 'surveys#publish'
        put 'close', to: 'surveys#close'
      end
    end

    put '/locales/enable/:id', to: 'locales#enable'
    put '/locales/disable/:id', to: 'locales#disable'

    resources :pages
    put '/pages/enable/:id', to: 'pages#enable'
    put '/pages/disable/:id', to: 'pages#disable'

    put '/page_category/enable/:id', to: 'page_categories#enable'
    put '/page_category/disable/:id', to: 'page_categories#disable'
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  include Statusable
  include ActiveModel::Validations
  include AASM

  has_many :answers, dependent: :delete_all

  accepts_nested_attributes_for :answers

  validates :question, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates_with SurveyValidator, on: :create

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :published, :closed

    event :published do
      transitions from: :pending, to: :published
    end

    event :closed do
      transitions from: :published, to: :closed
    end
  end

  def self.surveys_list_by_statuses(status_opened)
    query = status_opened ? pending_or_published : closed
    query.select("surveys.*, count(answers_users.user_id) as responses")
      .left_outer_joins(answers: [:answers_users])
      .group("surveys.id")
  end

  def self.filter(params)
    query = params[:status].nil? || params[:status] == "published" ? published : closed
    if params[:search].present?
      query = query.where("lower(question) like ?", "%#{params[:search].downcase}%")
    end
    if params[:sort_by].present?
      query = query.order(params[:sort_by] == "newest" ? "start_at" : "end_at")
    end
    query
  end

  def self.newest_published_unvoted(user)
    published.where
      .not(id: user.answers.pluck(:survey_id))
      .order(start_at: :desc)
      .first
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::AdminController
  include Admin::Concerns::Statusable

  PER_PAGE = 20

  def index
    @status_opened = params[:status].nil? || params[:status] == "opened"
    @surveys = Survey.surveys_list_by_statuses(@status_opened).paginate(page: params[:page], per_page: PER_PAGE)
    @opened = Survey.pending_or_published.count
    @closed = Survey.closed.count
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to admin_surveys_path, notice: "Survey was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    model.destroy
    redirect_to admin_surveys_path, notice: "Survey was successfully destroyed."
  end

  private

  def survey_params
    params.require(:survey).permit(:question, :start_at, :end_at, answers_attributes: [:answer])
  end

  def model
    @model ||= Survey.find(params[:id])
  end
end

app/controllers/surveys_controller.rb
class SurveysController < PortalController
  before_action :authenticate_user!

  PER_PAGE = 20

  def index
    @surveys = Survey.filter(params).paginate(page: params[:page], per_page: PER_PAGE)
    @status = params[:status]
  end

  def show
    @answers = Answer.answers_with_votes_count(survey.id)
    @total = SurveysHelper.calculate_total(@answers)
    @user_answer = current_user.answers.where(id: @answers.pluck(:id)).first
    render :show, layout: false
  end

  def show_newest
    @survey = Survey.newest_published_unvoted(current_user)
    @user_answer = nil
    @answers = @survey ? @survey.answers : []
    render :show, layout: false
  end

  def update
    answer = Answer.find(params[:survey][:answer_id].to_i)
    current_user.answers << answer
    redirect_back fallback_location: root_path
  end

  private

  def survey
    @survey ||= Survey.find(params[:id])
  end
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
  extend Admin::StatusableHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def self.calculate_total(answers)
    answers.reduce(0) { |sum, answer| sum + answer.votes }
  end
end

app/views/admin/surveys/_status.html.slim
.dropdown
  - if survey.pending? || survey.published?
    button[type="button" data-toggle="dropdown" aria-expanded="false" id="dropdownMenuButton#{survey.id}" class=" btn dropdown-toggle #{status(survey)[:class]}"]
      = status(survey)[:text]
    ul.dropdown-menu[aria-labelledby="dropdownMenuButton"]
      - if survey.pending?
        li
          span.survey.dropdown-item[data-id="#{survey.id}" data-action="publish"]
            | Publish
      li
        span.survey.dropdown-item[data-id="#{survey.id}" data-action="close"]
          | Close
  - else

app/views/admin/surveys/index.html.slim
p#notice
  = notice
= render 'admin/title', title: 'Surveys', link_text: '+ Add survey', link_path: new_admin_survey_path
= render 'layouts/categories_list'
= link_to admin_surveys_path(status: 'opened'), class: 'nav-sport'
  = "Opened (#{@opened})"
= link_to admin_surveys_path(status: 'closed'), class: 'nav-sport'
  = "Closed (#{@closed})"
div
  .row
    - unless @surveys.nil?
      table.table
        thead
          tr
            th
              | Question
            - if @status_opened
              th
                | Status
            th
              | Responses
            th
              br
        tbody
          - @surveys.each do |survey|
            tr
              td
                = survey.question
              - if @status_opened
                td
                  = render 'admin/surveys/status', survey: survey
              td
                = survey.responses
              td
                = link_to admin_survey_path(survey), class: 'btn btn-sm', method: :delete, data: { confirm: 'Are you sure?' }
                  svg.bi.bi-basket-fill[xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewbox="0 0 16 16"]
                    path[d="M5.071 1.243a.5.5 0 0 1 .858.514L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 6h1.717L5.07 1.243zM3.5 10.5a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0v-3z"]
  = will_paginate @surveys

app/views/admin/surveys/new.html.slim
= render 'admin/title', title: 'New Banner', link_text: '+ Add banner', link_path: new_admin_survey_path
= render 'layouts/categories_list'
= form_with(model: @survey, url: admin_surveys_path) do |form|
  - if @survey.errors.any?
    #error_explanation
      h2
        = pluralize(@survey.errors.count, "error")
        |  prohibited this banner from being saved:
      ul
        - @survey.errors.each do |error|
          li
            = error.full_message
  .form-group
    = form.label :question, class: 'label'
    = form.text_field :question, class: 'form-control'
  .form-group
    = form.label :start_at, class: 'label'
    input.form-control[type="date" name="survey[start_at]"]
  .form-group
    = form.label :end_at, class: 'label'
    input.form-control[type="date" name="survey[end_at]"]
  = form.label 'Answers', class: 'label'
  #answers
    .form-group
      input.form-control[type="text" name="survey[answers_attributes][][answer]"]
  .form-group
    button.btn.btn-primary#add-answer[type="button"]
      | + Add
  .form-group
    = form.submit nil, class: 'btn btn-primary'