config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'main#index'

  devise_for :users, controllers: {
    sessions: 'auth/sessions',
    registrations: 'auth/registrations'
  }

  resources :categories do
    resources :articles do
      resources :comments
    end
    resources :banners, only: :index
  end

  get '/search', to: 'articles#search'

  resources :reactions
  resources :surveys
  resources :teams, only: [:index, :destroy] do
    member do
      post 'attach-to-user', to: 'teams#attach_to_user'
    end
  end

  get '/teams-search', to: 'teams#search'
  get '/team-hub', to: 'teams#team_hub'

  get '/survey/show_newest', to: 'surveys#show_newest'

  get '/profile', to: 'users#edit'
  put '/profile', to: 'users#update'
  patch '/newsletter/subscribe', to: 'users#subscribe_to_newsletter'

  get '/pages/:slug', to: 'pages#show'

  get '/locale/:locale', to: 'main#locale'

  namespace 'admin' do
    root 'home#index'
    put '/settings/:key', to: 'home#update'
    post 'home/photo_of_the_day', to: 'home#photo_of_the_day'
    resources :categories do
      member do
        get 'subcategories'
      end
      resources :articles
    end
    resources :users
    resources :locales
    resources :banners do
      member do
        put 'publish', to: 'banners#publish'
        put 'close', to: 'banners#close'
      end
    end
    resources :teams

    resources :surveys do
      member do
        put 'publish', to: 'surveys#publish'
        put 'close', to: 'surveys#close'
      end
    end

    put '/locales/enable/:id', to: 'locales#enable'
    put '/locales/disable/:id', to: 'locales#disable'

    resources :pages
    put '/pages/enable/:id', to: 'pages#enable'
    put '/pages/disable/:id', to: 'pages#disable'

    put '/page_category/enable/:id', to: 'page_categories#enable'
    put '/page_category/disable/:id', to: 'page_categories#disable'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :team
  has_many :comments, dependent: :delete_all
  has_many :article_views, dependent: :delete_all
  mount_uploader :image, ImageUploader
  before_save :prepare_video_link
  scope :most_popular, -> { order(views_count: :desc).limit(3) }
  scope :most_commented, -> { order(comments_count: :desc).limit(3) }

  def self.search(query)
    where("lower(title) like :query or lower(body) like :query ", query: "%#{query}%")
      .eager_load(:category)
  end

  def self.reset_views(article_ids)
    if article_ids.empty?
      update_all(views_count: 0)
    else
      where.not(id: article_ids).update_all(views_count: 0)
    end
  end

  def self.reset_comments(article_ids)
    if article_ids.empty?
      update_all(comments_count: 0)
    else
      where.not(id: article_ids).update_all(comments_count: 0)
    end
  end

  private

  YOUTUBE_URL = "https://www.youtube-nocookie.com/embed/"

  def prepare_video_link
    return if video_link.nil?
    matches = video_link.match(/watch\?v=([\w\-]*)/)
    if matches.present?
      self.video_link = matches.captures.nil? ?
      nil :
      "#{YOUTUBE_URL}#{matches.captures.first}"
    end
  end
end

app/models/article_view.rb
class ArticleView < ApplicationRecord
  belongs_to :article
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

class Admin::ArticlesController < Admin::AdminController
  PER_PAGE = 10

  def index
    @category = Category.find(params[:category_id])
    @articles = @category.articles.paginate(page: params[:page], per_page: PER_PAGE)
  end

  def show
    article
  end

  def new
    @article = Article.new
    @categories = Category.all
    @teams = Team.all
    @category = Category.find(params[:category_id])
  end

  def edit
    @categories = Category.all
    @teams = Team.all
    article
  end

  def create
    @categories = Category.all
    @teams = Team.all
    @article = Article.new(article_params)
    if @article.save
      SendNewsletters.perform_later(@article)
      redirect_to admin_category_article_path @article.category, @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @categories = Category.all
    @teams = Team.all
    if article.update(article_params)
      redirect_to admin_category_article_path article.category, article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    article.destroy
    redirect_to admin_category_articles_path article.category, notice: "Article was successfully destroyed."
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :caption, :body, :category_id, :image, :video_link, :team_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < PortalController
  PER_PAGE = 20

  def index
    @category = Category.find(params[:category_id])
    @articles = @category.articles.paginate(page: params[:page], per_page: PER_PAGE)
  end

  def show
    article
    @article.article_views.create
    @comments_details = ArticleCommentsPresenter.new(article, current_user, params[:page])
    @comment = current_user.nil? ? Comment.new : current_user.comments.new
  end

  def search
    @query = params[:query]
    @articles = params[:query] ? Article.search(@query.downcase) : []
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def get_search_fragment(article, query)
    text = article.title.downcase.include?(query) ? article.title.downcase : article.body.downcase
    position = text.index(query)
    start = position - 100 > 0 ? position - 100 : 0
    finish = position + 100 + query.length
    text = text.gsub!(query, "<strong>#{query}</strong>")
    text[start..finish]
  end
end

app/views/admin/articles/_form.html.slim
= form_with(model: article, url: url) do |form|
  - if article.errors.any?
    #error_explanation
      h2
        = pluralize(article.errors.count, "error")
        |  prohibited this article from being saved:
      ul
        - article.errors.each do |error|
          li
            = error.full_message
  .form-group
    = form.label :title, class: 'label'
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :caption, class: 'label'
    = form.text_field :caption, class: 'form-control'
  .form-group
    = form.label :body, class: 'label'
    = form.text_area :body, class: 'form-control', id: 'article_body'
  .form-group
    = form.label :category_id, class: 'label'
    = form.select :category_id, options_for_select(@categories, @article.category_id), {}, class: 'form-control'
  .form-group
    = form.label :image, class: 'label'
    = form.file_field :image
  .form-group
    = form.label :video_link, class: 'label'
    = form.text_field :video_link, class: 'form-control'
  .form-group
    = form.submit nil, class: 'btn btn-primary'

app/views/admin/articles/edit.html.slim
= render 'admin/title', title: 'Editing Article', link_text: '+ Add article', link_path: new_admin_category_article_path(@article.category_id)
= render 'layouts/categories_list'
= render 'form', article: @article, url: admin_category_article_path(@article.category_id)

app/views/admin/articles/index.html.slim
p#notice
  = notice
= render 'admin/title', title: @category.name, link_text: '+ Add article', link_path: new_admin_category_article_path
= render 'layouts/categories_list'
.articles-container
  .row
    - @articles.each do |article|
      .col-md-12.admin-article
        - unless article.image.file.nil?
          = image_tag article.image.thumb.url
        .card-body
          h5.card-title.admin-article-title
          div
            = link_to link_to article.title, admin_category_article_path(@category, article)
          .dropdown-toggle-article[data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false" data-reference="parent"]
            span
              svg.bi.bi-three-dots[xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewbox="0 0 16 16"]
                path[d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"]
          .dropdown-menu.dropdown-menu-right
            = link_to 'Destroy', admin_category_article_path(@category, article), class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure?' }
            = link_to 'Edit', edit_admin_category_article_path(@category, article), class: 'dropdown-item'
          p.card-text
            = article.caption
= will_paginate @articles

app/views/admin/articles/new.html.slim
= render 'admin/title', title: 'New Article', link_text: '+ Add article', link_path: new_admin_category_article_path(@category)
= render 'layouts/categories_list'
= render 'form', article: @article, url: admin_category_articles_path(@category)

app/views/admin/articles/show.html.slim
p#notice
  = notice
= render 'admin/title', title: @article.title, link_text: '+ Add article', link_path: new_admin_category_article_path(@article.category_id)
= render 'layouts/categories_list'
p
  strong
    | Title: 
  = @article.title
p
  strong
    | Caption:
  = @article.caption
p
  strong
    | Body: 
  = sanitize @article.body
p
  strong
    | Category: 
  = @article.category.name
p
  strong
    | Image: 
  - unless @article.image.file.nil?
    = image_tag @article.image.url
p
  strong
    | Video: 
  - if @article.video_link
    iframe[width="560" height="315" src="#{@article.video_link}" title="YouTube video player" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen]