config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'main#index'

  devise_for :users, controllers: {
    sessions: 'auth/sessions',
    registrations: 'auth/registrations'
  }

  resources :categories do
    resources :articles do
      resources :comments
    end
    resources :banners, only: :index
  end

  get '/search', to: 'articles#search'

  resources :reactions
  resources :surveys
  resources :teams, only: [:index, :destroy] do
    member do
      post 'attach-to-user', to: 'teams#attach_to_user'
    end
  end

  get '/teams-search', to: 'teams#search'
  get '/team-hub', to: 'teams#team_hub'

  get '/survey/show_newest', to: 'surveys#show_newest'

  get '/profile', to: 'users#edit'
  put '/profile', to: 'users#update'
  patch '/newsletter/subscribe', to: 'users#subscribe_to_newsletter'

  get '/pages/:slug', to: 'pages#show'

  get '/locale/:locale', to: 'main#locale'

  namespace 'admin' do
    root 'home#index'
    put '/settings/:key', to: 'home#update'
    post 'home/photo_of_the_day', to: 'home#photo_of_the_day'
    resources :categories do
      member do
        get 'subcategories'
      end
      resources :articles
    end
    resources :users
    resources :locales
    resources :banners do
      member do
        put 'publish', to: 'banners#publish'
        put 'close', to: 'banners#close'
      end
    end
    resources :teams

    resources :surveys do
      member do
        put 'publish', to: 'surveys#publish'
        put 'close', to: 'surveys#close'
      end
    end

    put '/locales/enable/:id', to: 'locales#enable'
    put '/locales/disable/:id', to: 'locales#disable'

    resources :pages
    put '/pages/enable/:id', to: 'pages#enable'
    put '/pages/disable/:id', to: 'pages#disable'

    put '/page_category/enable/:id', to: 'page_categories#enable'
    put '/page_category/disable/:id', to: 'page_categories#disable'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :team
  has_many :comments, dependent: :delete_all
  has_many :article_views, dependent: :delete_all
  mount_uploader :image, ImageUploader
  before_save :prepare_video_link
  scope :most_popular, -> { order(views_count: :desc).limit(3) }
  scope :most_commented, -> { order(comments_count: :desc).limit(3) }

  def self.search(query)
    where("lower(title) like :query or lower(body) like :query ", query: "%#{query}%")
      .eager_load(:category)
  end

  def self.reset_views(article_ids)
    if article_ids.empty?
      update_all(views_count: 0)
    else
      where.not(id: article_ids).update_all(views_count: 0)
    end
  end

  def self.reset_comments(article_ids)
    if article_ids.empty?
      update_all(comments_count: 0)
    else
      where.not(id: article_ids).update_all(comments_count: 0)
    end
  end

  private

  YOUTUBE_URL = "https://www.youtube-nocookie.com/embed/"

  def prepare_video_link
    return if video_link.nil?
    matches = video_link.match(/watch\?v=([\w\-]*)/)
    if matches.present?
      self.video_link = matches.captures.nil? ?
      nil :
      "#{YOUTUBE_URL}#{matches.captures.first}"
    end
  end
end

app/models/article_view.rb
class ArticleView < ApplicationRecord
  belongs_to :article
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

class Admin::ArticlesController < Admin::AdminController
  PER_PAGE = 10

  def index
    @category = Category.find(params[:category_id])
    @articles = @category.articles.paginate(page: params[:page], per_page: PER_PAGE)
  end

  def show
    article
  end

  def new
    @article = Article.new
    @categories = Category.all
    @teams = Team.all
    @category = Category.find(params[:category_id])
  end

  def edit
    @categories = Category.all
    @teams = Team.all
    article
  end

  def create
    @categories = Category.all
    @teams = Team.all
    @article = Article.new(article_params)
    if @article.save
      SendNewsletters.perform_later(@article)
      redirect_to admin_category_article_path @article.category, @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @categories = Category.all
    @teams = Team.all
    if article.update(article_params)
      redirect_to admin_category_article_path article.category, article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    article.destroy
    redirect_to admin_category_articles_path article.category, notice: "Article was successfully destroyed."
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :caption, :body, :category_id, :image, :video_link, :team_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < PortalController
  PER_PAGE = 20

  def index
    @category = Category.find(params[:category_id])
    @articles = @category.articles.paginate(page: params[:page], per_page: PER_PAGE)
  end

  def show
    article
    @article.article_views.create
    @comments_details = ArticleCommentsPresenter.new(article, current_user, params[:page])
    @comment = current_user.nil? ? Comment.new : current_user.comments.new
  end

  def search
    @query = params[:query]
    @articles = params[:query] ? Article.search(@query.downcase) : []
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def get_search_fragment(article, query)
    text = article.title.downcase.include?(query) ? article.title.downcase : article.body.downcase
    position = text.index(query)
    start = position - 100 > 0 ? position - 100 : 0
    finish = position + 100 + query.length
    text = text.gsub!(query, "<strong>#{query}</strong>")
    text[start..finish]
  end
end

app/views/articles/_comment.html.slim
.comment
  h5
    strong
      - unless comment.user.avatar.file.nil?
        = image_tag comment.user.avatar.tiny.url, class: 'avatar-tiny'
      = comment.user.full_name
  .date-block
    span.date
      = comment.created_at.strftime('%b %e')
    - if comment.edited?
      = t('edited')
  p[id="comment_#{comment.id}"]
    = comment.comment
  div.comments-block
    .comment-button
      - if @comments_details.user_likes_comments.any? { |reaction| reaction.comment_id == comment.id }
        = render 'components/liked', comment: comment, reaction: @comments_details.user_likes_comments.first { |reaction| reaction.comment_id == comment.id }
      - else
        = render 'components/like', comment: comment
      = comment.likes_count
    .comment-button
      - if @comments_details.user_dislikes_comments.any? { |reaction| reaction.comment_id == comment.id }
        = render 'components/disliked', comment: comment, reaction: @comments_details.user_dislikes_comments.first { |reaction| reaction.comment_id == comment.id }
      - else
        = render 'components/dislike', comment: comment
      = comment.dislikes_count
    - if policy(comment).destroy?
      .comment-button
        = link_to t('delete'), category_article_comment_path(@article.category, @article, comment), method: :delete
    - if policy(comment).update?
      .comment-button
        span.edit-comment[data-url="#{category_article_comment_path(@article.category, @article, comment)}" data-id="#{comment.id}"]
          = t('edit')

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.slim
h1#category_id[data-category_id="#{@category.id}"]
  = @category.name
.articles-container
  - @articles.each do |article|
    = link_to category_article_url(@category.id, article.id) do
      .card.article-item
        - unless article.image.file.nil?
          = image_tag article.image.thumb.url, class: "card-img-top"
        .card-body
          h5.card-title
            = article.title
          p.card-text
            = article.caption
= will_paginate @articles
= content_for :banner_place do
  #banner-place

app/views/articles/search.html.slim
h1
  = "#{@query} (#{@articles.count})"
div
  - @articles.each do |article|
    div.article-in-search
      div
        h5
          = link_to category_article_url(article.category_id, article.id) do
            = "#{article.category.name} > #{article.title}"
        p
          = sanitize get_search_fragment(article, @query)

app/views/articles/show.html.slim
h1#category_id[data-category_id="#{@article.category.id}"]
  = @article.title
h4
  = link_to @article.category.name, category_articles_url(@article.category)
- unless @article.image.file.nil?
  .row
    .col-md-12
      = image_tag @article.image.url
.row
  .col-md-12
    br
- unless @article.video_link.nil? || @article.video_link == ''
  .row
    .col-md-12
      iframe[width="560" height="315" src="#{@article.video_link}" title="YouTube video player" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen]
div
  = sanitize @article.body
br
.comments
  .comments-header
    = t('comments') + "(#{@comments_details.comments.count})"
  div.comments-wrapper
    - if policy(@comment).create?
      = form_with model: @comments_details.comments, url: category_article_comments_path(@article.category, @article),  method: :post, id: 'form', class: 'add-comment' do |form|
        = form.text_field :comment, class: 'form-control', id: "comment_field", required: true
        = form.hidden_field :edit_comment_url, id: "edit_comment_url"
        = form.hidden_field :article_id, id: "article_id", value: @article.id
        = form.button t('cancel'), type: 'button', class: 'btn btn-info', hidden: true, id: 'cancel_button'
        = form.button t('submit'), class: 'btn btn-primary', id: 'submit_button'
    div.comments-wrapper
      - @comments_details.comments.each do |comment|
        = render "articles/comment", comment: comment
      = will_paginate @comments_details.comments
= content_for :banner_place do
  #banner-place